const CARD_ACTIONS = {
    GET_CARDS_START: 'GET_CARDS_START',
    GET_CARDS_SUCCESS: 'GET_CARDS_SUCCESS',
    GET_CARDS_FAILURE: 'GET_CARDS_FAILURE',
    CREATE_CARD: 'CREATE_CARD',
    UPDATE_CARD: 'UPDATE_CARD',
    DELETE_CARDS: 'DELETE_CARDS'
};

const PAGE_ACTIONS = {
    UPDATE_READONLY: 'UPDATE_READONLY'
};

export {
    CARD_ACTIONS,
    PAGE_ACTIONS
};
